export const FETCH_CUSTOMERS = 'FETCH_CUSTOMERS';

export const SET_CUSTOMERS_START = 'SET_CUSTOMERS_START';
export const SET_CUSTOMERS_SUCCESS = 'SET_CUSTOMERS_SUCCESS';
export const SET_CUSTOMERS_FAILURE = 'SET_CUSTOMERS_FAILURE';

export const REMOVE_CUSTOMER = 'REMOVE_CUSTOMER';
